/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dXRvh2hLoyh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function calendar() {
  return (
    <div className="rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
      <div className="flex items-center justify-between border-b px-4 py-3 dark:border-gray-800">
        <div className="flex items-center gap-2">
          <button className="rounded-md p-1 transition-colors hover:bg-gray-100 dark:hover:bg-gray-800">
            <ChevronLeftIcon className="h-5 w-5" />
          </button>
          <div className="text-sm font-medium">May 2024</div>
          <button className="rounded-md p-1 transition-colors hover:bg-gray-100 dark:hover:bg-gray-800">
            <ChevronRightIcon className="h-5 w-5" />
          </button>
        </div>
      </div>
      <div className="grid grid-cols-7 p-4 gap-1.5">
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Sun
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Mon
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Tue
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Wed
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Thu
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Fri
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          Sat
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          25
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          26
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          27
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          28
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          29
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          30
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          1
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          2
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          3
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          4
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          5
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium text-gray-500 dark:text-gray-400">
          6
        </div>
        <div className="flex h-8 w-8 items-center justify-center text-xs font-medium bg-gray-900 text-white rounded-full dark:bg-gray-50">
          7
        </div>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
